#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThiBangLaiAndroid")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBoDe(BoDe instance);
    partial void UpdateBoDe(BoDe instance);
    partial void DeleteBoDe(BoDe instance);
    partial void InsertCauHoi(CauHoi instance);
    partial void UpdateCauHoi(CauHoi instance);
    partial void DeleteCauHoi(CauHoi instance);
    partial void InsertChiTietBoDe(ChiTietBoDe instance);
    partial void UpdateChiTietBoDe(ChiTietBoDe instance);
    partial void DeleteChiTietBoDe(ChiTietBoDe instance);
    partial void InsertChiTietKetQua(ChiTietKetQua instance);
    partial void UpdateChiTietKetQua(ChiTietKetQua instance);
    partial void DeleteChiTietKetQua(ChiTietKetQua instance);
    partial void InsertDangKi(DangKi instance);
    partial void UpdateDangKi(DangKi instance);
    partial void DeleteDangKi(DangKi instance);
    partial void InsertKetQua(KetQua instance);
    partial void UpdateKetQua(KetQua instance);
    partial void DeleteKetQua(KetQua instance);
    partial void InsertLoaiCauHoi(LoaiCauHoi instance);
    partial void UpdateLoaiCauHoi(LoaiCauHoi instance);
    partial void DeleteLoaiCauHoi(LoaiCauHoi instance);
    partial void InsertManHinh(ManHinh instance);
    partial void UpdateManHinh(ManHinh instance);
    partial void DeleteManHinh(ManHinh instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    partial void InsertNguoiDungManHinh(NguoiDungManHinh instance);
    partial void UpdateNguoiDungManHinh(NguoiDungManHinh instance);
    partial void DeleteNguoiDungManHinh(NguoiDungManHinh instance);
    partial void InsertThongTinNguoiDung(ThongTinNguoiDung instance);
    partial void UpdateThongTinNguoiDung(ThongTinNguoiDung instance);
    partial void DeleteThongTinNguoiDung(ThongTinNguoiDung instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LinqToSql.Properties.Settings.Default.ThiBangLaiAndroidConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BoDe> BoDes
		{
			get
			{
				return this.GetTable<BoDe>();
			}
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietBoDe> ChiTietBoDes
		{
			get
			{
				return this.GetTable<ChiTietBoDe>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietKetQua> ChiTietKetQuas
		{
			get
			{
				return this.GetTable<ChiTietKetQua>();
			}
		}
		
		public System.Data.Linq.Table<DangKi> DangKis
		{
			get
			{
				return this.GetTable<DangKi>();
			}
		}
		
		public System.Data.Linq.Table<KetQua> KetQuas
		{
			get
			{
				return this.GetTable<KetQua>();
			}
		}
		
		public System.Data.Linq.Table<LoaiCauHoi> LoaiCauHois
		{
			get
			{
				return this.GetTable<LoaiCauHoi>();
			}
		}
		
		public System.Data.Linq.Table<ManHinh> ManHinhs
		{
			get
			{
				return this.GetTable<ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDungManHinh> NguoiDungManHinhs
		{
			get
			{
				return this.GetTable<NguoiDungManHinh>();
			}
		}
		
		public System.Data.Linq.Table<ThongTinNguoiDung> ThongTinNguoiDungs
		{
			get
			{
				return this.GetTable<ThongTinNguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BoDe")]
	public partial class BoDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBoDe;
		
		private string _TenBoDe;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<ChiTietBoDe> _ChiTietBoDes;
		
		private EntitySet<DangKi> _DangKis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBoDeChanging(int value);
    partial void OnMaBoDeChanged();
    partial void OnTenBoDeChanging(string value);
    partial void OnTenBoDeChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public BoDe()
		{
			this._ChiTietBoDes = new EntitySet<ChiTietBoDe>(new Action<ChiTietBoDe>(this.attach_ChiTietBoDes), new Action<ChiTietBoDe>(this.detach_ChiTietBoDes));
			this._DangKis = new EntitySet<DangKi>(new Action<DangKi>(this.attach_DangKis), new Action<DangKi>(this.detach_DangKis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBoDe
		{
			get
			{
				return this._MaBoDe;
			}
			set
			{
				if ((this._MaBoDe != value))
				{
					this.OnMaBoDeChanging(value);
					this.SendPropertyChanging();
					this._MaBoDe = value;
					this.SendPropertyChanged("MaBoDe");
					this.OnMaBoDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBoDe", DbType="NVarChar(50)")]
		public string TenBoDe
		{
			get
			{
				return this._TenBoDe;
			}
			set
			{
				if ((this._TenBoDe != value))
				{
					this.OnTenBoDeChanging(value);
					this.SendPropertyChanging();
					this._TenBoDe = value;
					this.SendPropertyChanged("TenBoDe");
					this.OnTenBoDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(150)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoDe_ChiTietBoDe", Storage="_ChiTietBoDes", ThisKey="MaBoDe", OtherKey="MaBoDe")]
		public EntitySet<ChiTietBoDe> ChiTietBoDes
		{
			get
			{
				return this._ChiTietBoDes;
			}
			set
			{
				this._ChiTietBoDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoDe_DangKi", Storage="_DangKis", ThisKey="MaBoDe", OtherKey="MaBoDe")]
		public EntitySet<DangKi> DangKis
		{
			get
			{
				return this._DangKis;
			}
			set
			{
				this._DangKis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBoDes(ChiTietBoDe entity)
		{
			this.SendPropertyChanging();
			entity.BoDe = this;
		}
		
		private void detach_ChiTietBoDes(ChiTietBoDe entity)
		{
			this.SendPropertyChanging();
			entity.BoDe = null;
		}
		
		private void attach_DangKis(DangKi entity)
		{
			this.SendPropertyChanging();
			entity.BoDe = this;
		}
		
		private void detach_DangKis(DangKi entity)
		{
			this.SendPropertyChanging();
			entity.BoDe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCauHoi;
		
		private System.Nullable<int> _MaLoaiCauHoi;
		
		private string _NoiDungCauHoi;
		
		private string _DapAnA;
		
		private string _DapAnB;
		
		private string _DapAnC;
		
		private string _DapAnD;
		
		private string _DapAnDung;
		
		private string _HinhAnh;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<ChiTietBoDe> _ChiTietBoDes;
		
		private EntitySet<ChiTietKetQua> _ChiTietKetQuas;
		
		private EntityRef<LoaiCauHoi> _LoaiCauHoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauHoiChanging(int value);
    partial void OnMaCauHoiChanged();
    partial void OnMaLoaiCauHoiChanging(System.Nullable<int> value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnNoiDungCauHoiChanging(string value);
    partial void OnNoiDungCauHoiChanged();
    partial void OnDapAnAChanging(string value);
    partial void OnDapAnAChanged();
    partial void OnDapAnBChanging(string value);
    partial void OnDapAnBChanged();
    partial void OnDapAnCChanging(string value);
    partial void OnDapAnCChanged();
    partial void OnDapAnDChanging(string value);
    partial void OnDapAnDChanged();
    partial void OnDapAnDungChanging(string value);
    partial void OnDapAnDungChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public CauHoi()
		{
			this._ChiTietBoDes = new EntitySet<ChiTietBoDe>(new Action<ChiTietBoDe>(this.attach_ChiTietBoDes), new Action<ChiTietBoDe>(this.detach_ChiTietBoDes));
			this._ChiTietKetQuas = new EntitySet<ChiTietKetQua>(new Action<ChiTietKetQua>(this.attach_ChiTietKetQuas), new Action<ChiTietKetQua>(this.detach_ChiTietKetQuas));
			this._LoaiCauHoi = default(EntityRef<LoaiCauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", DbType="Int")]
		public System.Nullable<int> MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					if (this._LoaiCauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCauHoi", DbType="NVarChar(MAX)")]
		public string NoiDungCauHoi
		{
			get
			{
				return this._NoiDungCauHoi;
			}
			set
			{
				if ((this._NoiDungCauHoi != value))
				{
					this.OnNoiDungCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCauHoi = value;
					this.SendPropertyChanged("NoiDungCauHoi");
					this.OnNoiDungCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnA", DbType="NVarChar(2000)")]
		public string DapAnA
		{
			get
			{
				return this._DapAnA;
			}
			set
			{
				if ((this._DapAnA != value))
				{
					this.OnDapAnAChanging(value);
					this.SendPropertyChanging();
					this._DapAnA = value;
					this.SendPropertyChanged("DapAnA");
					this.OnDapAnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnB", DbType="NVarChar(2000)")]
		public string DapAnB
		{
			get
			{
				return this._DapAnB;
			}
			set
			{
				if ((this._DapAnB != value))
				{
					this.OnDapAnBChanging(value);
					this.SendPropertyChanging();
					this._DapAnB = value;
					this.SendPropertyChanged("DapAnB");
					this.OnDapAnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnC", DbType="NVarChar(2000)")]
		public string DapAnC
		{
			get
			{
				return this._DapAnC;
			}
			set
			{
				if ((this._DapAnC != value))
				{
					this.OnDapAnCChanging(value);
					this.SendPropertyChanging();
					this._DapAnC = value;
					this.SendPropertyChanged("DapAnC");
					this.OnDapAnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnD", DbType="NVarChar(2000)")]
		public string DapAnD
		{
			get
			{
				return this._DapAnD;
			}
			set
			{
				if ((this._DapAnD != value))
				{
					this.OnDapAnDChanging(value);
					this.SendPropertyChanging();
					this._DapAnD = value;
					this.SendPropertyChanged("DapAnD");
					this.OnDapAnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="NVarChar(50)")]
		public string DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(MAX)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietBoDe", Storage="_ChiTietBoDes", ThisKey="MaCauHoi", OtherKey="MaCauHoi")]
		public EntitySet<ChiTietBoDe> ChiTietBoDes
		{
			get
			{
				return this._ChiTietBoDes;
			}
			set
			{
				this._ChiTietBoDes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietKetQua", Storage="_ChiTietKetQuas", ThisKey="MaCauHoi", OtherKey="MaCauHoi")]
		public EntitySet<ChiTietKetQua> ChiTietKetQuas
		{
			get
			{
				return this._ChiTietKetQuas;
			}
			set
			{
				this._ChiTietKetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiCauHoi_CauHoi", Storage="_LoaiCauHoi", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi", IsForeignKey=true)]
		public LoaiCauHoi LoaiCauHoi
		{
			get
			{
				return this._LoaiCauHoi.Entity;
			}
			set
			{
				LoaiCauHoi previousValue = this._LoaiCauHoi.Entity;
				if (((previousValue != value) 
							|| (this._LoaiCauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiCauHoi.Entity = null;
						previousValue.CauHois.Remove(this);
					}
					this._LoaiCauHoi.Entity = value;
					if ((value != null))
					{
						value.CauHois.Add(this);
						this._MaLoaiCauHoi = value.MaLoaiCauHoi;
					}
					else
					{
						this._MaLoaiCauHoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiCauHoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietBoDes(ChiTietBoDe entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_ChiTietBoDes(ChiTietBoDe entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
		
		private void attach_ChiTietKetQuas(ChiTietKetQua entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = this;
		}
		
		private void detach_ChiTietKetQuas(ChiTietKetQua entity)
		{
			this.SendPropertyChanging();
			entity.CauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietBoDe")]
	public partial class ChiTietBoDe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietBoDe;
		
		private System.Nullable<int> _MaBoDe;
		
		private string _MaThi;
		
		private System.Nullable<int> _MaCauHoi;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntityRef<BoDe> _BoDe;
		
		private EntityRef<CauHoi> _CauHoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietBoDeChanging(int value);
    partial void OnMaChiTietBoDeChanged();
    partial void OnMaBoDeChanging(System.Nullable<int> value);
    partial void OnMaBoDeChanged();
    partial void OnMaThiChanging(string value);
    partial void OnMaThiChanged();
    partial void OnMaCauHoiChanging(System.Nullable<int> value);
    partial void OnMaCauHoiChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public ChiTietBoDe()
		{
			this._BoDe = default(EntityRef<BoDe>);
			this._CauHoi = default(EntityRef<CauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietBoDe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietBoDe
		{
			get
			{
				return this._MaChiTietBoDe;
			}
			set
			{
				if ((this._MaChiTietBoDe != value))
				{
					this.OnMaChiTietBoDeChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietBoDe = value;
					this.SendPropertyChanged("MaChiTietBoDe");
					this.OnMaChiTietBoDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoDe", DbType="Int")]
		public System.Nullable<int> MaBoDe
		{
			get
			{
				return this._MaBoDe;
			}
			set
			{
				if ((this._MaBoDe != value))
				{
					if (this._BoDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBoDeChanging(value);
					this.SendPropertyChanging();
					this._MaBoDe = value;
					this.SendPropertyChanged("MaBoDe");
					this.OnMaBoDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThi", DbType="VarChar(10)")]
		public string MaThi
		{
			get
			{
				return this._MaThi;
			}
			set
			{
				if ((this._MaThi != value))
				{
					this.OnMaThiChanging(value);
					this.SendPropertyChanging();
					this._MaThi = value;
					this.SendPropertyChanged("MaThi");
					this.OnMaThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="Int")]
		public System.Nullable<int> MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoDe_ChiTietBoDe", Storage="_BoDe", ThisKey="MaBoDe", OtherKey="MaBoDe", IsForeignKey=true)]
		public BoDe BoDe
		{
			get
			{
				return this._BoDe.Entity;
			}
			set
			{
				BoDe previousValue = this._BoDe.Entity;
				if (((previousValue != value) 
							|| (this._BoDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BoDe.Entity = null;
						previousValue.ChiTietBoDes.Remove(this);
					}
					this._BoDe.Entity = value;
					if ((value != null))
					{
						value.ChiTietBoDes.Add(this);
						this._MaBoDe = value.MaBoDe;
					}
					else
					{
						this._MaBoDe = default(Nullable<int>);
					}
					this.SendPropertyChanged("BoDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietBoDe", Storage="_CauHoi", ThisKey="MaCauHoi", OtherKey="MaCauHoi", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.ChiTietBoDes.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.ChiTietBoDes.Add(this);
						this._MaCauHoi = value.MaCauHoi;
					}
					else
					{
						this._MaCauHoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietKetQua")]
	public partial class ChiTietKetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChiTietKQ;
		
		private System.Nullable<int> _MaKetQua;
		
		private System.Nullable<int> _MaCauHoi;
		
		private string _DapAnChon;
		
		private System.Nullable<bool> _KetQua;
		
		private EntityRef<CauHoi> _CauHoi;
		
		private EntityRef<KetQua> _KetQua1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietKQChanging(int value);
    partial void OnMaChiTietKQChanged();
    partial void OnMaKetQuaChanging(System.Nullable<int> value);
    partial void OnMaKetQuaChanged();
    partial void OnMaCauHoiChanging(System.Nullable<int> value);
    partial void OnMaCauHoiChanged();
    partial void OnDapAnChonChanging(string value);
    partial void OnDapAnChonChanged();
    partial void OnKetQuaChanging(System.Nullable<bool> value);
    partial void OnKetQuaChanged();
    #endregion
		
		public ChiTietKetQua()
		{
			this._CauHoi = default(EntityRef<CauHoi>);
			this._KetQua1 = default(EntityRef<KetQua>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietKQ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChiTietKQ
		{
			get
			{
				return this._MaChiTietKQ;
			}
			set
			{
				if ((this._MaChiTietKQ != value))
				{
					this.OnMaChiTietKQChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietKQ = value;
					this.SendPropertyChanged("MaChiTietKQ");
					this.OnMaChiTietKQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKetQua", DbType="Int")]
		public System.Nullable<int> MaKetQua
		{
			get
			{
				return this._MaKetQua;
			}
			set
			{
				if ((this._MaKetQua != value))
				{
					if (this._KetQua1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKetQuaChanging(value);
					this.SendPropertyChanging();
					this._MaKetQua = value;
					this.SendPropertyChanged("MaKetQua");
					this.OnMaKetQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="Int")]
		public System.Nullable<int> MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					if (this._CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnChon", DbType="VarChar(50)")]
		public string DapAnChon
		{
			get
			{
				return this._DapAnChon;
			}
			set
			{
				if ((this._DapAnChon != value))
				{
					this.OnDapAnChonChanging(value);
					this.SendPropertyChanging();
					this._DapAnChon = value;
					this.SendPropertyChanged("DapAnChon");
					this.OnDapAnChonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQua", DbType="Bit")]
		public System.Nullable<bool> KetQua
		{
			get
			{
				return this._KetQua;
			}
			set
			{
				if ((this._KetQua != value))
				{
					this.OnKetQuaChanging(value);
					this.SendPropertyChanging();
					this._KetQua = value;
					this.SendPropertyChanged("KetQua");
					this.OnKetQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CauHoi_ChiTietKetQua", Storage="_CauHoi", ThisKey="MaCauHoi", OtherKey="MaCauHoi", IsForeignKey=true)]
		public CauHoi CauHoi
		{
			get
			{
				return this._CauHoi.Entity;
			}
			set
			{
				CauHoi previousValue = this._CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CauHoi.Entity = null;
						previousValue.ChiTietKetQuas.Remove(this);
					}
					this._CauHoi.Entity = value;
					if ((value != null))
					{
						value.ChiTietKetQuas.Add(this);
						this._MaCauHoi = value.MaCauHoi;
					}
					else
					{
						this._MaCauHoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("CauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQua_ChiTietKetQua", Storage="_KetQua1", ThisKey="MaKetQua", OtherKey="MaKetQua", IsForeignKey=true)]
		public KetQua KetQua1
		{
			get
			{
				return this._KetQua1.Entity;
			}
			set
			{
				KetQua previousValue = this._KetQua1.Entity;
				if (((previousValue != value) 
							|| (this._KetQua1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KetQua1.Entity = null;
						previousValue.ChiTietKetQuas.Remove(this);
					}
					this._KetQua1.Entity = value;
					if ((value != null))
					{
						value.ChiTietKetQuas.Add(this);
						this._MaKetQua = value.MaKetQua;
					}
					else
					{
						this._MaKetQua = default(Nullable<int>);
					}
					this.SendPropertyChanged("KetQua1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKi")]
	public partial class DangKi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDangKy;
		
		private System.Nullable<System.DateTime> _NgayDangKy;
		
		private System.Nullable<bool> _TinhTrang;
		
		private System.Nullable<int> _MaNguoiDung;
		
		private System.Nullable<int> _MaBoDe;
		
		private EntitySet<KetQua> _KetQuas;
		
		private EntityRef<BoDe> _BoDe;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDangKyChanging(int value);
    partial void OnMaDangKyChanged();
    partial void OnNgayDangKyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKyChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    partial void OnMaNguoiDungChanging(System.Nullable<int> value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaBoDeChanging(System.Nullable<int> value);
    partial void OnMaBoDeChanged();
    #endregion
		
		public DangKi()
		{
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			this._BoDe = default(EntityRef<BoDe>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDangKy
		{
			get
			{
				return this._MaDangKy;
			}
			set
			{
				if ((this._MaDangKy != value))
				{
					this.OnMaDangKyChanging(value);
					this.SendPropertyChanging();
					this._MaDangKy = value;
					this.SendPropertyChanged("MaDangKy");
					this.OnMaDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDangKy
		{
			get
			{
				return this._NgayDangKy;
			}
			set
			{
				if ((this._NgayDangKy != value))
				{
					this.OnNgayDangKyChanging(value);
					this.SendPropertyChanging();
					this._NgayDangKy = value;
					this.SendPropertyChanged("NgayDangKy");
					this.OnNgayDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="Int")]
		public System.Nullable<int> MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBoDe", DbType="Int")]
		public System.Nullable<int> MaBoDe
		{
			get
			{
				return this._MaBoDe;
			}
			set
			{
				if ((this._MaBoDe != value))
				{
					if (this._BoDe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBoDeChanging(value);
					this.SendPropertyChanging();
					this._MaBoDe = value;
					this.SendPropertyChanged("MaBoDe");
					this.OnMaBoDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKi_KetQua", Storage="_KetQuas", ThisKey="MaDangKy", OtherKey="MaDangKy")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BoDe_DangKi", Storage="_BoDe", ThisKey="MaBoDe", OtherKey="MaBoDe", IsForeignKey=true)]
		public BoDe BoDe
		{
			get
			{
				return this._BoDe.Entity;
			}
			set
			{
				BoDe previousValue = this._BoDe.Entity;
				if (((previousValue != value) 
							|| (this._BoDe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BoDe.Entity = null;
						previousValue.DangKis.Remove(this);
					}
					this._BoDe.Entity = value;
					if ((value != null))
					{
						value.DangKis.Add(this);
						this._MaBoDe = value.MaBoDe;
					}
					else
					{
						this._MaBoDe = default(Nullable<int>);
					}
					this.SendPropertyChanged("BoDe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DangKi", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.DangKis.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.DangKis.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.DangKi = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.DangKi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQua")]
	public partial class KetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKetQua;
		
		private System.Nullable<int> _DapAnDung;
		
		private System.Nullable<int> _DapAnSai;
		
		private string _GhiChu;
		
		private System.Nullable<int> _MaDangKy;
		
		private System.Nullable<System.DateTime> _NgayLam;
		
		private System.Nullable<bool> _DaXoa;
		
		private EntitySet<ChiTietKetQua> _ChiTietKetQuas;
		
		private EntityRef<DangKi> _DangKi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKetQuaChanging(int value);
    partial void OnMaKetQuaChanged();
    partial void OnDapAnDungChanging(System.Nullable<int> value);
    partial void OnDapAnDungChanged();
    partial void OnDapAnSaiChanging(System.Nullable<int> value);
    partial void OnDapAnSaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaDangKyChanging(System.Nullable<int> value);
    partial void OnMaDangKyChanged();
    partial void OnNgayLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLamChanged();
    partial void OnDaXoaChanging(System.Nullable<bool> value);
    partial void OnDaXoaChanged();
    #endregion
		
		public KetQua()
		{
			this._ChiTietKetQuas = new EntitySet<ChiTietKetQua>(new Action<ChiTietKetQua>(this.attach_ChiTietKetQuas), new Action<ChiTietKetQua>(this.detach_ChiTietKetQuas));
			this._DangKi = default(EntityRef<DangKi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKetQua", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKetQua
		{
			get
			{
				return this._MaKetQua;
			}
			set
			{
				if ((this._MaKetQua != value))
				{
					this.OnMaKetQuaChanging(value);
					this.SendPropertyChanging();
					this._MaKetQua = value;
					this.SendPropertyChanged("MaKetQua");
					this.OnMaKetQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="Int")]
		public System.Nullable<int> DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnSai", DbType="Int")]
		public System.Nullable<int> DapAnSai
		{
			get
			{
				return this._DapAnSai;
			}
			set
			{
				if ((this._DapAnSai != value))
				{
					this.OnDapAnSaiChanging(value);
					this.SendPropertyChanging();
					this._DapAnSai = value;
					this.SendPropertyChanged("DapAnSai");
					this.OnDapAnSaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDangKy", DbType="Int")]
		public System.Nullable<int> MaDangKy
		{
			get
			{
				return this._MaDangKy;
			}
			set
			{
				if ((this._MaDangKy != value))
				{
					if (this._DangKi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDangKyChanging(value);
					this.SendPropertyChanging();
					this._MaDangKy = value;
					this.SendPropertyChanged("MaDangKy");
					this.OnMaDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLam", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLam
		{
			get
			{
				return this._NgayLam;
			}
			set
			{
				if ((this._NgayLam != value))
				{
					this.OnNgayLamChanging(value);
					this.SendPropertyChanging();
					this._NgayLam = value;
					this.SendPropertyChanged("NgayLam");
					this.OnNgayLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaXoa", DbType="Bit")]
		public System.Nullable<bool> DaXoa
		{
			get
			{
				return this._DaXoa;
			}
			set
			{
				if ((this._DaXoa != value))
				{
					this.OnDaXoaChanging(value);
					this.SendPropertyChanging();
					this._DaXoa = value;
					this.SendPropertyChanged("DaXoa");
					this.OnDaXoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KetQua_ChiTietKetQua", Storage="_ChiTietKetQuas", ThisKey="MaKetQua", OtherKey="MaKetQua")]
		public EntitySet<ChiTietKetQua> ChiTietKetQuas
		{
			get
			{
				return this._ChiTietKetQuas;
			}
			set
			{
				this._ChiTietKetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DangKi_KetQua", Storage="_DangKi", ThisKey="MaDangKy", OtherKey="MaDangKy", IsForeignKey=true)]
		public DangKi DangKi
		{
			get
			{
				return this._DangKi.Entity;
			}
			set
			{
				DangKi previousValue = this._DangKi.Entity;
				if (((previousValue != value) 
							|| (this._DangKi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DangKi.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._DangKi.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaDangKy = value.MaDangKy;
					}
					else
					{
						this._MaDangKy = default(Nullable<int>);
					}
					this.SendPropertyChanged("DangKi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietKetQuas(ChiTietKetQua entity)
		{
			this.SendPropertyChanging();
			entity.KetQua1 = this;
		}
		
		private void detach_ChiTietKetQuas(ChiTietKetQua entity)
		{
			this.SendPropertyChanging();
			entity.KetQua1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiCauHoi")]
	public partial class LoaiCauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiCauHoi;
		
		private string _TenLoaiCauHoi;
		
		private EntitySet<CauHoi> _CauHois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiCauHoiChanging(int value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnTenLoaiCauHoiChanging(string value);
    partial void OnTenLoaiCauHoiChanged();
    #endregion
		
		public LoaiCauHoi()
		{
			this._CauHois = new EntitySet<CauHoi>(new Action<CauHoi>(this.attach_CauHois), new Action<CauHoi>(this.detach_CauHois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiCauHoi", DbType="NVarChar(500)")]
		public string TenLoaiCauHoi
		{
			get
			{
				return this._TenLoaiCauHoi;
			}
			set
			{
				if ((this._TenLoaiCauHoi != value))
				{
					this.OnTenLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiCauHoi = value;
					this.SendPropertyChanged("TenLoaiCauHoi");
					this.OnTenLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiCauHoi_CauHoi", Storage="_CauHois", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi")]
		public EntitySet<CauHoi> CauHois
		{
			get
			{
				return this._CauHois;
			}
			set
			{
				this._CauHois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.LoaiCauHoi = this;
		}
		
		private void detach_CauHois(CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.LoaiCauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManHinh")]
	public partial class ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaManHinh;
		
		private string _TenManHinh;
		
		private string _GhiChu;
		
		private EntitySet<NguoiDungManHinh> _NguoiDungManHinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(int value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public ManHinh()
		{
			this._NguoiDungManHinhs = new EntitySet<NguoiDungManHinh>(new Action<NguoiDungManHinh>(this.attach_NguoiDungManHinhs), new Action<NguoiDungManHinh>(this.detach_NguoiDungManHinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(100)")]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_NguoiDungManHinh", Storage="_NguoiDungManHinhs", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<NguoiDungManHinh> NguoiDungManHinhs
		{
			get
			{
				return this._NguoiDungManHinhs;
			}
			set
			{
				this._NguoiDungManHinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiDungManHinhs(NguoiDungManHinh entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = this;
		}
		
		private void detach_NguoiDungManHinhs(NguoiDungManHinh entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiDung;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _TinhTrang;
		
		private EntitySet<DangKi> _DangKis;
		
		private EntitySet<NguoiDungManHinh> _NguoiDungManHinhs;
		
		private EntitySet<ThongTinNguoiDung> _ThongTinNguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(int value);
    partial void OnMaNguoiDungChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public NguoiDung()
		{
			this._DangKis = new EntitySet<DangKi>(new Action<DangKi>(this.attach_DangKis), new Action<DangKi>(this.detach_DangKis));
			this._NguoiDungManHinhs = new EntitySet<NguoiDungManHinh>(new Action<NguoiDungManHinh>(this.attach_NguoiDungManHinhs), new Action<NguoiDungManHinh>(this.detach_NguoiDungManHinhs));
			this._ThongTinNguoiDungs = new EntitySet<ThongTinNguoiDung>(new Action<ThongTinNguoiDung>(this.attach_ThongTinNguoiDungs), new Action<ThongTinNguoiDung>(this.detach_ThongTinNguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_DangKi", Storage="_DangKis", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<DangKi> DangKis
		{
			get
			{
				return this._DangKis;
			}
			set
			{
				this._DangKis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDungManHinh", Storage="_NguoiDungManHinhs", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<NguoiDungManHinh> NguoiDungManHinhs
		{
			get
			{
				return this._NguoiDungManHinhs;
			}
			set
			{
				this._NguoiDungManHinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ThongTinNguoiDung", Storage="_ThongTinNguoiDungs", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<ThongTinNguoiDung> ThongTinNguoiDungs
		{
			get
			{
				return this._ThongTinNguoiDungs;
			}
			set
			{
				this._ThongTinNguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKis(DangKi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_DangKis(DangKi entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_NguoiDungManHinhs(NguoiDungManHinh entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_NguoiDungManHinhs(NguoiDungManHinh entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
		
		private void attach_ThongTinNguoiDungs(ThongTinNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = this;
		}
		
		private void detach_ThongTinNguoiDungs(ThongTinNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDungManHinh")]
	public partial class NguoiDungManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiDungManHinh;
		
		private System.Nullable<int> _MaNguoiDung;
		
		private System.Nullable<int> _MaManHinh;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _TinhTrang;
		
		private EntityRef<ManHinh> _ManHinh;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungManHinhChanging(int value);
    partial void OnMaNguoiDungManHinhChanged();
    partial void OnMaNguoiDungChanging(System.Nullable<int> value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaManHinhChanging(System.Nullable<int> value);
    partial void OnMaManHinhChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnTinhTrangChanging(System.Nullable<bool> value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public NguoiDungManHinh()
		{
			this._ManHinh = default(EntityRef<ManHinh>);
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDungManHinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiDungManHinh
		{
			get
			{
				return this._MaNguoiDungManHinh;
			}
			set
			{
				if ((this._MaNguoiDungManHinh != value))
				{
					this.OnMaNguoiDungManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDungManHinh = value;
					this.SendPropertyChanged("MaNguoiDungManHinh");
					this.OnMaNguoiDungManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="Int")]
		public System.Nullable<int> MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="Int")]
		public System.Nullable<int> MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(150)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="Bit")]
		public System.Nullable<bool> TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_NguoiDungManHinh", Storage="_ManHinh", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public ManHinh ManHinh
		{
			get
			{
				return this._ManHinh.Entity;
			}
			set
			{
				ManHinh previousValue = this._ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManHinh.Entity = null;
						previousValue.NguoiDungManHinhs.Remove(this);
					}
					this._ManHinh.Entity = value;
					if ((value != null))
					{
						value.NguoiDungManHinhs.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(Nullable<int>);
					}
					this.SendPropertyChanged("ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_NguoiDungManHinh", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.NguoiDungManHinhs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.NguoiDungManHinhs.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThongTinNguoiDung")]
	public partial class ThongTinNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThongTinNguoiDung;
		
		private System.Nullable<int> _MaNguoiDung;
		
		private string _HoTen;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _Hinh;
		
		private EntityRef<NguoiDung> _NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThongTinNguoiDungChanging(int value);
    partial void OnMaThongTinNguoiDungChanged();
    partial void OnMaNguoiDungChanging(System.Nullable<int> value);
    partial void OnMaNguoiDungChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    #endregion
		
		public ThongTinNguoiDung()
		{
			this._NguoiDung = default(EntityRef<NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThongTinNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThongTinNguoiDung
		{
			get
			{
				return this._MaThongTinNguoiDung;
			}
			set
			{
				if ((this._MaThongTinNguoiDung != value))
				{
					this.OnMaThongTinNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaThongTinNguoiDung = value;
					this.SendPropertyChanged("MaThongTinNguoiDung");
					this.OnMaThongTinNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="Int")]
		public System.Nullable<int> MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(500)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(50)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDung_ThongTinNguoiDung", Storage="_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public NguoiDung NguoiDung
		{
			get
			{
				return this._NguoiDung.Entity;
			}
			set
			{
				NguoiDung previousValue = this._NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDung.Entity = null;
						previousValue.ThongTinNguoiDungs.Remove(this);
					}
					this._NguoiDung.Entity = value;
					if ((value != null))
					{
						value.ThongTinNguoiDungs.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
